include Makefile.src

INCLUDE = -I$(SHAREDINC) -I$(CDIR)/include/
CFILES  = $(wildcard *.c)
OFILES  = $(CFILES:%.c=%.o)
EXEC    = $(CFILES:%.c=%)
OPT     = -ggdb3
CFLAGS  = -Wall -Wextra $(OPT) $(INCLUDE)

$(EXEC):$(OFILES)
	$(E) $(CC_STR) $@
	$(Q) $(CC) -o $@ $<

%.o:%.c
	$(E) $(CC_STR) $@
	$(Q) $(CC) $(CFLAGS) -c -o $(@) $<

clean:
	$(Q) $(RM) -f $(OFILES) $(EXEC)
